using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AESTest
{

    public enum CurlStatus : int
    {
        Ok = 0,
        UnsupportedProtocol = 1,
        FailedInit = 2,
        UrlMalformat = 3,
        NotBuiltIn = 4,
        CouldntResolveProxy = 5,
        CouldntResolveHost = 6,
        CouldntConnect = 7,
        WeirdServerReply = 8,
        RemoteAccessDenied = 9,
        FtpAcceptFailed = 10,
        FtpWeirdPassReply = 11,
        FtpAcceptTimeout = 12,
        FtpWeirdPasvReply = 13,
        FtpWeird227Format = 14,
        FtpCantGetHost = 15,
        Http2 = 16,
        FtpCouldntSetType = 17,
        PartialFile = 18,
        FtpCouldntRetrFile = 19,
        QuoteError = 21,
        HttpReturnedError = 22,
        WriteError = 23,
        UploadFailed = 25,
        ReadError = 26,
        OutOfMemory = 27,
        OperationTimedout = 28,
        FtpPortFailed = 30,
        FtpCouldntUseRest = 31,
        RangeError = 33,
        HttpPostError = 34,
        SslConnectError = 35,
        BadDownloadResume = 36,
        FileCouldntReadFile = 37,
        LdapCannotBind = 38,
        LdapSearchFailed = 39,
        FunctionNotFound = 41,
        AbortedByCallback = 42,
        BadFunctionArgument = 43,
        InterfaceFailed = 45,
        TooManyRedirects = 47,
        UnknownOption = 48,
        SetoptOptionSyntax = 49,
        GotNothing = 52,
        SslEngineNotfound = 53,
        SslEngineSetfailed = 54,
        SendError = 55,
        RecvError = 56,
        SslCertproblem = 58,
        SslCipher = 59,
        PeerFailedVerification = 60,
        BadContentEncoding = 61,
        FilesizeExceeded = 63,
        UseSslFailed = 64,
        SendFailRewind = 65,
        SslEngineInitfailed = 66,
        LoginDenied = 67,
        TftpNotfound = 68,
        TftpPerm = 69,
        RemoteDiskFull = 70,
        TftpIllegal = 71,
        TftpUnknownid = 72,
        RemoteFileExists = 73,
        TftpNosuchuser = 74,
        SslCacertBadfile = 77,
        RemoteFileNotFound = 78,
        Ssh = 79,
        SslShutdownFailed = 80,
        Again = 81,
        SslCrlBadfile = 82,
        SslIssuerError = 83,
        FtpPretFailed = 84,
        RtspCseqError = 85,
        RtspSessionError = 86,
        FtpBadFileList = 87,
        ChunkFailed = 88,
        NoConnectionAvailable = 89,
        SslPinnedpubkeynotmatch = 90,
        SslInvalidcertstatus = 91,
        Http2Stream = 92,
        RecursiveApiCall = 93,
        AuthError = 94,
        Http3 = 95,
        QuicConnectError = 96,
        Proxy = 97,
        SslClientcert = 98,
        UnrecoverablePoll = 99,
    }
}
